[default]
DEBUG = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "app.ext.db:init_app",
    "app.ext.migrate:init_app",
    "app.ext.api:init_app"
]

[development]

[test]
SQLALCHEMY_DATABASE_URI = "sqlite://foodfy-test.db"

[production]
