[default]
DEBUG = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
    "app.ext.database:init_app",
    "app.ext.migrate:init_app",
    "app.ext.api:init_app"
]

[development]
DEBUG = true

[test]
SQLALCHEMY_DATABASE_URI = "sqlite:///test.db"

[production]
