"""Adicionando campos de data na tabela de chef

Revision ID: 5d97a698bd7f
Revises: abc07b126068
Create Date: 2020-12-14 23:37:54.386378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d97a698bd7f'
down_revision = 'abc07b126068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FFILES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('PATH', sa.String(length=100), nullable=True),
    sa.Column('CREATEDAT', sa.DateTime(), nullable=True),
    sa.Column('MODIFIEDAT', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('FCHEF',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=100), nullable=True),
    sa.Column('FILEID', sa.Integer(), nullable=True),
    sa.Column('CREATEDAT', sa.DateTime(), nullable=True),
    sa.Column('MODIFIEDAT', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['FILEID'], ['FFILES.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.drop_table('chef')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('FIID', sa.INTEGER(), server_default=sa.text('nextval(\'"files_FIID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('FINAME', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('FIPATH', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('CREATEDAT', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('MODIFIEDAT', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('FIID', name='files_pkey')
    )
    op.create_table('chef',
    sa.Column('CHID', sa.INTEGER(), server_default=sa.text('nextval(\'"chef_CHID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('CHNAME', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('CHID', name='chef_pkey')
    )
    op.drop_table('FCHEF')
    op.drop_table('FFILES')
    # ### end Alembic commands ###
