"""create table recipe and recipe_files

Revision ID: 7ef62646b31c
Revises: 517335c27c6c
Create Date: 2021-08-19 20:37:31.103753

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ef62646b31c"
down_revision = "517335c27c6c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe",
        sa.Column("id", sa.String(), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("ingredients", sa.JSON(), nullable=True),
        sa.Column("preparation", sa.JSON(), nullable=True),
        sa.Column("additional_information", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("chef_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chef_id"],
            ["chef.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe")
    # ### end Alembic commands ###
