"""Adicionando banco de dados

Revision ID: abc07b126068
Revises: 
Create Date: 2020-12-14 23:27:19.986007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc07b126068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('CHID', sa.Integer(), nullable=False),
    sa.Column('CHNAME', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('CHID')
    )
    op.create_table('files',
    sa.Column('FIID', sa.Integer(), nullable=False),
    sa.Column('FINAME', sa.String(length=100), nullable=True),
    sa.Column('FIPATH', sa.String(length=100), nullable=True),
    sa.Column('CREATEDAT', sa.DateTime(), nullable=True),
    sa.Column('MODIFIEDAT', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('FIID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('chef')
    # ### end Alembic commands ###
