"""Adicionando campos nulos e default

Revision ID: fa3c503cba50
Revises: 5d97a698bd7f
Create Date: 2020-12-14 23:47:03.123885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa3c503cba50'
down_revision = '5d97a698bd7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FCHEF', 'CREATEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('FCHEF', 'MODIFIEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('FCHEF', 'NAME',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('FFILES', 'CREATEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('FFILES', 'MODIFIEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('FFILES', 'NAME',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('FFILES', 'PATH',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('FFILES', 'PATH',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('FFILES', 'NAME',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('FFILES', 'MODIFIEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('FFILES', 'CREATEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('FCHEF', 'NAME',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('FCHEF', 'MODIFIEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('FCHEF', 'CREATEDAT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
